version: '3.7'

services:
  elasticsearch:
    build:
      context: ELK/elasticsearch/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - type: bind
        source: ./ELK/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - tyk

  logstash:
    build:
      context: ELK/logstash/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - type: bind
        source: ./ELK/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5001:5001/tcp"
      - "5001:5001/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - tyk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ELK/kibana/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - type: bind
        source: ./ELK/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - tyk
    depends_on:
      - elasticsearch

networks:
  tyk:
  

volumes:
  elasticsearch:

