// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_backend

type Address struct {
	Street     *string `json:"street"`
	City       *string `json:"city"`
	PostalCode *string `json:"postalCode"`
	Country    *string `json:"country"`
}

type AddressInput struct {
	Street     string `json:"street"`
	City       string `json:"city"`
	PostalCode string `json:"postalCode"`
	Country    string `json:"country"`
}

type NewTransaction struct {
	Sender    string `json:"sender"`
	Recipient string `json:"recipient"`
	Amount    int    `json:"amount"`
}

type NewUserInput struct {
	Balance int    `json:"balance"`
	Name    string `json:"name"`
	Email   string `json:"email"`
}

type Transaction struct {
	ID        string `json:"id"`
	Date      string `json:"date"`
	Amount    int    `json:"amount"`
	Sender    *User  `json:"sender"`
	Recipient *User  `json:"recipient"`
}

type UpdateUserDetailsInput struct {
	Name    *string       `json:"name"`
	Address *AddressInput `json:"address"`
}

type User struct {
	ID           string         `json:"id"`
	Balance      int            `json:"balance"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	Address      *Address       `json:"address"`
	Transactions []*Transaction `json:"transactions"`
}
