version: "3.7"

services:
  splunk:
    image: splunk/splunk:latest
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - elastic-data:/opt/splunk/etc
      - kibana-data:/opt/splunk/var
      - logstash-data:/opt/splunk/var
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=mypassword
    networks:
      - tyk

volumes:
  elastic-data:
  kibana-data:
  logstash-data:

networks:
  tyk:
    external:
      name: tyk-bank_tyk
